---
- name: Deploy WAR to Tomcat
  hosts: tomcat_servers
  vars:
    war_file: hello-1.0.war
    war_src_path: "/var/lib/jenkins/workspace/ansible/target/{{ war_file }}"
    tomcat_webapps_path: /opt/tomcat9/webapps
    tomcat_service_name: tomcat

  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: "{{ war_src_path }}"
        dest: "{{ tomcat_webapps_path }}/{{ war_file }}"
        mode: '0644'
      become: yes

    - name: Restart Tomcat service
      systemd:
        name: "{{ tomcat_service_name }}"
        state: restarted
      become: yes
